# Generated by Django 4.2.16 on 2026-01-04 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_tags',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='is_member_exclusive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Detailed product content'),
        ),
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='createTime in Node.js'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='dis_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount price (disPrice in Node.js)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gid',
            field=models.CharField(default=django.utils.timezone.now, help_text='Product ID from Node.js', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='has_recommend',
            field=models.IntegerField(default=0, help_text='0=normal, 1=recommended (hasRecommend in Node.js)'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_top',
            field=models.IntegerField(default=0, help_text='0=normal, 1=pinned (hasTop in Node.js)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_tier_required',
            field=models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0, help_text='Sold quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1, help_text='1=active, -1=inactive'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='updateTime in Node.js'),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, help_text='View count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0, help_text='Stock quantity'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gid'], name='products_gid_99a1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_top', 'has_recommend'], name='products_has_top_5119bd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['create_time'], name='products_create__041bbe_idx'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='products.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['tag'], name='product_tag_tag_6361c8_idx'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['product'], name='product_tag_product_2909de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together={('product', 'tag')},
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='product_ima_product_c8c86a_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='product_ima_product_93d64d_idx'),
        ),
    ]
