# Generated by Django 4.2.16 on 2026-01-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_producttag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(help_text='Banner image URL', max_length=500)),
                ('title', models.CharField(help_text='Jump link/title', max_length=200)),
                ('type', models.IntegerField(choices=[(1, '小程序内部'), (2, '外部小程序'), (3, '外部网站')], default=1, help_text='Jump type: 1=internal, 2=external mini-program, 3=external website')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether banner is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='banners_is_acti_d19f5a_idx'), models.Index(fields=['created_at'], name='banners_created_9e788a_idx')],
            },
        ),
    ]
