# Generated by Django 4.2.16 on 2026-01-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cover',
            field=models.CharField(help_text='Banner image URL (can be relative path like /static/banner.png or full URL)', max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(help_text='Image URL (can be relative path like /static/beef/xxx.jpg or full URL)', max_length=500),
        ),
    ]
