# Generated by Django 4.2.16 on 2026-01-08 04:56

import apps.products.models.product_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_change_image_url_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file', null=True, upload_to=apps.products.models.product_image.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image URL (auto-filled from uploaded image or manual entry)', max_length=500),
        ),
    ]
