# Generated by Django 4.2.16 on 2026-01-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_image_field_to_productimage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_gid_99a1dd_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gid',
        ),
    ]
