# Generated by Django 4.2.16 on 2026-01-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_gid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Product specification in kilograms (规格，单位：公斤)', max_digits=10),
        ),
    ]
