# Generated by Django 4.2.16 on 2026-01-03 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('available_points', models.IntegerField(default=0)),
                ('lifetime_earned', models.IntegerField(default=0)),
                ('lifetime_redeemed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Account',
                'verbose_name_plural': 'Points Accounts',
                'db_table': 'points_accounts',
            },
        ),
        migrations.CreateModel(
            name='PointsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('purchase', 'Purchase'), ('registration', 'Registration'), ('first_purchase', 'First Purchase'), ('review', 'Product Review'), ('referral', 'Referral'), ('birthday', 'Birthday Bonus'), ('redemption', 'Redemption')], max_length=20, unique=True)),
                ('points_amount', models.IntegerField()),
                ('is_percentage', models.BooleanField(default=False)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_points_per_transaction', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Points Rule',
                'verbose_name_plural': 'Points Rules',
                'db_table': 'points_rules',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earning', 'Points Earned'), ('redemption', 'Points Redeemed'), ('expiration', 'Points Expired'), ('adjustment', 'Manual Adjustment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='points.pointsaccount')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'db_table': 'points_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_amount', models.IntegerField()),
                ('remaining_points', models.IntegerField()),
                ('earned_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('is_fully_redeemed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expirations', to='points.pointsaccount')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.pointstransaction')),
            ],
            options={
                'verbose_name': 'Points Expiration',
                'verbose_name_plural': 'Points Expirations',
                'db_table': 'points_expirations',
                'ordering': ['expiry_date'],
            },
        ),
    ]
