# Generated by Django 4.2.16 on 2026-01-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
