# Generated by Django 4.2.16 on 2026-01-04 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wechat_pay', 'WeChat Pay'), ('alipay', 'Alipay'), ('bank_card', 'Bank Card'), ('balance', 'Account Balance')], max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for frontend', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is available')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order in frontend')),
                ('config', models.JSONField(default=dict, help_text='Payment method configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Internal transaction ID', max_length=100, unique=True)),
                ('order_id', models.CharField(help_text='Related order ID (roid)', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='CNY', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='pending', max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, help_text='External payment system transaction ID', max_length=200)),
                ('external_order_id', models.CharField(blank=True, help_text='External payment system order ID', max_length=200)),
                ('wechat_openid', models.CharField(blank=True, help_text='WeChat user OpenID', max_length=100)),
                ('wechat_prepay_id', models.CharField(blank=True, help_text='WeChat prepay ID', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Transaction creation time')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Payment completion time', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='Payment expiration time', null=True)),
                ('payment_data', models.JSONField(default=dict, help_text='Additional payment information')),
                ('callback_data', models.JSONField(default=dict, help_text='Payment callback data from external system')),
                ('callback_received_at', models.DateTimeField(blank=True, help_text='Callback received time', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code if payment failed', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_type', models.CharField(choices=[('payment', 'Payment Callback'), ('refund', 'Refund Callback')], max_length=10)),
                ('payment_method', models.CharField(help_text='Payment method that sent callback', max_length=50)),
                ('request_method', models.CharField(help_text='HTTP method (GET/POST)', max_length=10)),
                ('request_path', models.CharField(help_text='Request path', max_length=200)),
                ('request_headers', models.JSONField(default=dict, help_text='Request headers')),
                ('request_body', models.TextField(help_text='Raw request body')),
                ('request_ip', models.GenericIPAddressField(help_text='Client IP address')),
                ('processed', models.BooleanField(default=False, help_text='Whether callback was processed successfully')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('transaction_id', models.CharField(blank=True, help_text='Related transaction ID', max_length=100)),
                ('refund_id', models.CharField(blank=True, help_text='Related refund ID', max_length=100)),
                ('response_status', models.IntegerField(help_text='HTTP response status code')),
                ('response_body', models.TextField(help_text='Response body sent back')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_callbacks',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['callback_type'], name='payment_cal_callbac_4bb7cc_idx'), models.Index(fields=['payment_method'], name='payment_cal_payment_c0d22c_idx'), models.Index(fields=['transaction_id'], name='payment_cal_transac_e2e678_idx'), models.Index(fields=['refund_id'], name='payment_cal_refund__7191f7_idx'), models.Index(fields=['received_at'], name='payment_cal_receive_61714e_idx'), models.Index(fields=['processed'], name='payment_cal_process_7169e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeChatPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(help_text='WeChat App ID', max_length=100)),
                ('mch_id', models.CharField(help_text='WeChat Merchant ID', max_length=100)),
                ('nonce_str', models.CharField(help_text='Random string for signature', max_length=32)),
                ('body', models.CharField(help_text='Product description', max_length=128)),
                ('out_trade_no', models.CharField(help_text='Merchant order number', max_length=32)),
                ('total_fee', models.IntegerField(help_text='Total fee in cents (分)')),
                ('spbill_create_ip', models.GenericIPAddressField(help_text='Client IP address')),
                ('prepay_id', models.CharField(blank=True, help_text='WeChat prepay ID', max_length=64)),
                ('code_url', models.URLField(blank=True, help_text='QR code URL for native payment')),
                ('transaction_id', models.CharField(blank=True, help_text='WeChat transaction ID', max_length=32)),
                ('bank_type', models.CharField(blank=True, help_text='Bank type', max_length=16)),
                ('settlement_total_fee', models.IntegerField(blank=True, help_text='Settlement fee', null=True)),
                ('cash_fee', models.IntegerField(blank=True, help_text='Cash fee', null=True)),
                ('sign', models.CharField(blank=True, help_text='WeChat Pay signature', max_length=32)),
                ('sign_type', models.CharField(default='MD5', help_text='Signature type', max_length=10)),
                ('wechat_data', models.JSONField(default=dict, help_text='Additional WeChat Pay response data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_payment', to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'wechat_payments',
                'indexes': [models.Index(fields=['out_trade_no'], name='wechat_paym_out_tra_5201c2_idx'), models.Index(fields=['transaction_id'], name='wechat_paym_transac_b432bf_idx'), models.Index(fields=['prepay_id'], name='wechat_paym_prepay__a215af_idx')],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(help_text='Internal refund ID', max_length=100, unique=True)),
                ('order_id', models.CharField(help_text='Related order ID (roid)', max_length=50)),
                ('return_order_id', models.CharField(blank=True, help_text='Return order ID (rrid)', max_length=50)),
                ('refund_type', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], default='full', max_length=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=10)),
                ('refund_reason', models.TextField(help_text='Reason for refund')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('external_refund_id', models.CharField(blank=True, help_text='External system refund ID', max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Refund request time')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Refund processing time', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Refund completion time', null=True)),
                ('refund_data', models.JSONField(default=dict, help_text='Additional refund information')),
                ('error_code', models.CharField(blank=True, help_text='Error code if refund failed', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if refund failed')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for refund processing')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin user who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['order_id'], name='refund_requ_order_i_09d9c8_idx'), models.Index(fields=['return_order_id'], name='refund_requ_return__920359_idx'), models.Index(fields=['status'], name='refund_requ_status_2691a2_idx'), models.Index(fields=['original_transaction'], name='refund_requ_origina_e04168_idx'), models.Index(fields=['requested_at'], name='refund_requ_request_70cfa9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order_id'], name='payment_tra_order_i_54c79b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user'], name='payment_tra_user_id_b3ceaf_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payment_tra_status_137fde_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['external_transaction_id'], name='payment_tra_externa_a7becb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['wechat_openid'], name='payment_tra_wechat__4840e6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='payment_tra_created_e43546_idx'),
        ),
    ]
