# Generated by Django 4.2.16 on 2026-01-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatpayment',
            name='body',
            field=models.CharField(blank=True, default='', help_text='Product description', max_length=128),
        ),
        migrations.AlterField(
            model_name='wechatpayment',
            name='nonce_str',
            field=models.CharField(blank=True, default='', help_text='Random string for signature (V2 API)', max_length=32),
        ),
        migrations.AlterField(
            model_name='wechatpayment',
            name='spbill_create_ip',
            field=models.GenericIPAddressField(blank=True, default='127.0.0.1', help_text='Client IP address (V2 API, optional for V3)', null=True),
        ),
    ]
