# Generated by Django 4.2.16 on 2026-01-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField(help_text='Store ID (lid)', unique=True)),
                ('location', models.JSONField(default=dict, help_text="GeoJSON Point: {type: 'Point', coordinates: [lng, lat]}")),
                ('name', models.CharField(help_text='Store name', max_length=200)),
                ('address', models.CharField(help_text='Store address', max_length=500)),
                ('detail', models.CharField(blank=True, default='', help_text='Detailed address', max_length=500)),
                ('phone', models.CharField(blank=True, default='', help_text='Store phone number', max_length=20)),
                ('start_time', models.CharField(blank=True, default='', help_text='Opening time (startTime in Node.js)', max_length=20)),
                ('end_time', models.CharField(blank=True, default='', help_text='Closing time (endTime in Node.js)', max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1, help_text='Store status: 1=active, 2=deleted')),
                ('img', models.CharField(blank=True, default='', help_text='Store image URL', max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Creation time (createTime in Node.js)')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='Last update time')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['lid'], name='stores_lid_9445ff_idx'), models.Index(fields=['status'], name='stores_status_ecb921_idx'), models.Index(fields=['name'], name='stores_name_b54c6a_idx'), models.Index(fields=['address'], name='stores_address_bf5d0c_idx')],
            },
        ),
    ]
