# Generated by Django 4.2.16 on 2026-01-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_store'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='store',
            name='stores_lid_9445ff_idx',
        ),
        migrations.RemoveField(
            model_name='store',
            name='lid',
        ),
    ]
