# Generated by Django 3.2.25 on 2026-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_security_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='Avatar URL stored in cloud storage', max_length=500, null=True),
        ),
    ]
