# Generated by Django 4.2.16 on 2026-01-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tier_start_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membership_status',
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('min_spending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('benefits', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membership_tiers',
                'ordering': ['min_spending'],
            },
        ),
        migrations.CreateModel(
            name='TierUpgradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('spending_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades_from', to='membership.membershiptier')),
                ('to_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades_to', to='membership.membershiptier')),
            ],
            options={
                'db_table': 'tier_upgrade_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
