# Generated by Django 4.2.16 on 2026-01-03 16:00

from django.db import migrations


def populate_initial_tiers(apps, schema_editor):
    """Populate initial membership tiers with correct thresholds"""
    MembershipTier = apps.get_model('membership', 'MembershipTier')
    
    # Create the four tiers with specified thresholds
    tiers = [
        {
            'name': 'bronze',
            'display_name': 'Bronze',
            'min_spending': 0,
            'max_spending': 999.99,
            'points_multiplier': 1.0,
            'benefits': {
                'free_shipping': False,
                'early_access': False,
                'priority_support': False,
                'exclusive_products': False
            }
        },
        {
            'name': 'silver',
            'display_name': 'Silver',
            'min_spending': 1000,
            'max_spending': 4999.99,
            'points_multiplier': 1.2,
            'benefits': {
                'free_shipping': True,
                'early_access': False,
                'priority_support': False,
                'exclusive_products': False
            }
        },
        {
            'name': 'gold',
            'display_name': 'Gold',
            'min_spending': 5000,
            'max_spending': 19999.99,
            'points_multiplier': 1.5,
            'benefits': {
                'free_shipping': True,
                'early_access': True,
                'priority_support': True,
                'exclusive_products': False
            }
        },
        {
            'name': 'platinum',
            'display_name': 'Platinum',
            'min_spending': 20000,
            'max_spending': None,
            'points_multiplier': 2.0,
            'benefits': {
                'free_shipping': True,
                'early_access': True,
                'priority_support': True,
                'exclusive_products': True
            }
        }
    ]
    
    for tier_data in tiers:
        MembershipTier.objects.get_or_create(
            name=tier_data['name'],
            defaults=tier_data
        )


def reverse_populate_tiers(apps, schema_editor):
    """Remove initial tiers"""
    MembershipTier = apps.get_model('membership', 'MembershipTier')
    MembershipTier.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_tiers, reverse_populate_tiers),
    ]
